### ISSUE TITLE
Webpack 4 - DeprecationWarning: Chunk.mapModules

### ISSUE THREAD

**Issue by mtraynham** [alexindigo/webpack-chunk-hash#17]
Webpack 4 is complaining of a deprecation warning:

```
(node:8040) DeprecationWarning: Chunk.mapModules: Use Array.from(chunk.modulesIterable, fn) instead
```

I believe it relates to [this particular line](https://github.com/alexindigo/webpack-chunk-hash/blob/master/index.js#L22).  Hopefully I can get around to a PR for this.

**Comment by alexindigo** [comment]
Hey, thanks for your interest. 
I'm curious what is the use case for this module with webpack@4?

_Reason I'm asking: It was created as workaround to shortcomings of webpack@2, and webpack@3 should have addressed that issues._

Thank you.

**Comment by mtraynham** [comment]
So, this is a good question as I can't particularly remember why I've kept using it, but only that it was consistent in producing the same hashes across builds, and even today it seems to do so, where Webpack does not.

I removed this plugin as a test and it seems intermittent that I get different chunkhash's across builds.  I'm not sure if that's related to https://github.com/webpack/webpack/issues/6623, which is fairly recent, but without the webpack-chunk-hash plugin, I'll get vendor files (using CommonChunk) named like follows:

vendor.717d59f0f1b557550a73.js
vendor.dfddbf05091859520abd.js
vendor.dfddbf05091859520abd.js
vendor.93e1357c712b12c0e2d8.js
vendor.93e1357c712b12c0e2d8.js
vendor.d0ebd85ac7dae6032076.js

Interestingly enough, the main entry point always seems to be consistent.
main.c381d39105dbce0ae67f.js

I am using the NamedModulesPlugin, according to the best practices of these articles, [1](https://webpack.js.org/guides/caching/#module-identifiers) & [2](https://gist.github.com/sokra/ff1b0290282bfa2c037bdb6dcca1a7aa#level-3-chunk), to ensure consistent filenames across builds, so I'm not sure where the discrepancy is actually happening.

Alternatively, using the webpack-chunk-hash, I consistently get a vendor file named:
vendor.9d8d7f9533a6694420fc.js

Functionally, I don't really understand when Webpack is generating that chunkhash or what it's actually using to create a hash, but if I were to take an educated guess, I assume it's not on the input of the code and rather on some form of the output which any number of plugins or loaders could change.

**Comment by KevinGrandon** [comment]
Yeah, we're seeing the same thing, inconsistent hashing in webpack 4, though this module fixes it for us. We'd love to continue using this with webpack 4, thanks for working on a fix!

**Comment by anthonybrown** [comment]
I'm seeing the same error, is this fixed now?

**Comment by mtraynham** [comment]
@anthonybrown This should be fixed in 0.6.0.  If you see the same error, add stack traces when running webpack with node the node trace-deprecation flag, i.e. `node --trace-deprecation ./node_modules/bin/webpack ....`.  This will help identify which module and line numbers you're seeing the error for.

**Comment by missx** [comment]
I'm still seeing the error. I'm using version 0.6.0 and webpack 4.

`(node:1266) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
/Users/ximena/Documents/Projects/westime-frontend/node_modules/webpack/lib/Chunk.js:750
		throw new Error(
		^

Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (/Users/ximena/Documents/Projects/westime-frontend/node_modules/webpack/lib/Chunk.js:750:9)
    at /Users/ximena/Documents/Projects/westime-frontend/node_modules/extract-text-webpack-plugin/dist/index.js:176:48
    at Array.forEach (<anonymous>)
    at /Users/ximena/Documents/Projects/westime-frontend/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/ximena/Documents/Projects/westime-frontend/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/ximena/Documents/Projects/westime-frontend/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/Users/ximena/Documents/Projects/westime-frontend/node_modules/webpack/lib/Compilation.js:905:27)
    at hooks.make.callAsync.err (/Users/ximena/Documents/Projects/westime-frontend/node_modules/webpack/lib/Compiler.js:494:17)
    at _err0 (eval at create (/Users/ximena/Documents/Projects/westime-frontend/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (/Users/ximena/Documents/Projects/westime-frontend/node_modules/webpack/lib/Compilation.js:771:12)
    at processModuleDependencies.err (/Users/ximena/Documents/Projects/westime-frontend/node_modules/webpack/lib/Compilation.js:710:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)`
